version: 0.2

env:
  variables:
    REPOSITORY_URI: "449325664824.dkr.ecr.eu-west-1.amazonaws.com/dev"
    IMAGE_TAG: "grafana-v1"
    CONTAINER_NAME: "grafana"

phases:
  build:
    commands:
      - echo "Preparing ECS image definitions..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json